version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      # Use the standard port for dev
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/uuid.sql:/docker-entrypoint-initdb.d/uuid.sqlbas
  postgres-jest:
    container_name: postgres-jest
    image: postgis/postgis
    networks:
      - webnet
    environment:
      POSTGRES_USER: jest
      POSTGRES_PASSWORD: jest
      POSTGRES_DB: jest
      PG_DATA: /var/lib/postgresql/data
    ports:
      # Use a different port for jest
      - 5433:5432
    volumes:
      - ./docker/uuid.sql:/docker-entrypoint-initdb.d/uuid.sql
  s3rver:
    container_name: s3rver
    build:
      dockerfile: Dockerfile
      context: ./docker/s3rver
    ports:
      - 9191:9191
    volumes:
      - ./s3:/tmp/s3rver

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      # https://github.com/localstack/localstack#configurations
      - SERVICES=sns,sqs
      - DEBUG=1
      - DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/mercanis-localstack}:/tmp/mercanis-localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  webnet:
volumes:
  pgdata:
