version: '3.7'

services:
  postgres:
    container_name: jest
    image: postgis/postgis
    networks:
      - webnet
    environment:
      POSTGRES_USER: jest
      POSTGRES_PASSWORD: jest
      POSTGRES_DB: jest
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./docker/uuid.sql:/docker-entrypoint-initdb.d/uuid.sql
networks:
  webnet:
