use_frameworks! :linkage => :static
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

project 'Fitlink',
'Development' => :debug,
'Development.Release' => :release

IS_CI = ENV['APPCENTER_BUILD_ID']

target 'Fitlink' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

#   pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'appcenter-core', :path => '../node_modules/appcenter'

  pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'

  pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes'

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

  target 'FitlinkTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

#   if not IS_CI
#     use_flipper!()
#   end

#   post_install do |installer|
#     $RNMBGL.post_install(installer)
#     react_native_post_install(installer)
#   end
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end
