export enum QueryKeys {
  Me = 'me',
  Following = 'me/following',
  Followers = 'me/followers',
  MyLeagues = 'me/leagues',
  LeagueInvitations = 'me/league-invitations',
  Leagues = 'leagues',
  League = 'league',
  LeagueRank = 'leagueRank',
  LeagueMembers = 'leagues/members',
  LeagueInvitableUsers = 'leagues/invitable-users',
  SearchLeagues = 'leagues/search',
  SearchUsers = 'users/search',
  User = 'user',
  UserGoals = 'user/goals',
  Rewards = 'rewards',
  MyRewards = 'me/rewards',
  Reward = 'reward',
  NextReward = 'me/next-reward',
  Sports = 'sports',
  SearchActivities = 'activities',
  SearchActivitiesMap = 'activities/map',
}
