name: Deploy

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
      DB_DATABASE_NAME: ${{ secrets.DEV_DB_DATABASE_NAME }}
      DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DB_PORT: ${{ secrets.DEV_DB_PORT }}
      API_PREFIX: ${{ secrets.DEV_API_PREFIX }}
      API_DOMAIN_NAME: ${{ secrets.DEV_API_DOMAIN_NAME }}
      API_DOMAIN_NAME_HOSTED_ZONE_ID: ${{ secrets.DEV_API_DOMAIN_NAME_HOSTED_ZONE_ID }}

      # This is the AWS API Gateway hosted proxy for imin, allowing the lambda function to reach it inside the VPC
      # https://eu-west-2.console.aws.amazon.com/apigateway/home?region=eu-west-2#/apis/a1udqh1r23/settings
      IMIN_API_BASE_URL: https://a1udqh1r23.execute-api.eu-west-2.amazonaws.com/imin-proxy/
      EMAIL_DEBUG: 0
      ENABLE_SWAGGER: 1

      # S3 configuration uses ARN / access point for VPC
      S3_BUCKET: develop-nest-fitlinkapp
      S3_USE_ACCESS_POINT: '1'
      S3_REGION: eu-west-2
      S3_PUBLIC_ENDPOINT: https://develop-nest-fitlinkapp.s3.eu-west-2.amazonaws.com



    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup docker
        run: docker-compose up -d postgres-jest s3rver

      - name: Allow docker postgres 10 seconds to startups
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'

      - name: Migrate and seed test database
        run: yarn migration:run -c jest && yarn migration:seed -c jest

      - name: Test e2e
        run: yarn run test

      - name: Stop docker
        run: docker-compose down

      - name: Build nest for Serverless
        run: yarn run build

      # - name: Install serverless globally
      #   run: yarn add global serverless

      # - name: Serverless - Run deploy
      #   if: github.ref == 'refs/heads/develop'
      #   run: yarn run sls:deploy

      # - name: Serverless - Run migrations
      #   if: github.ref == 'refs/heads/develop'
      #   run: yarn run sls:migrate

      - name: Regenerate UML if entities change
        if: github.ref == 'refs/heads/develop'
        run: |
          if(( $(git diff HEAD~1..HEAD apps/api/src/**/*entity.ts | LC_ALL=C.UTF-8 wc -m) != 0)); then
            yarn run db:diagram
            git add docs/uml.svg
            git commit -m "Update UML diagram - skip ci"
            git push origin develop
          fi


