name: React Native Build Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      yarn_cache_dir: ${{ steps.yarn_cache.outputs.dir }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: apps/mobile

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Get yarn cache directory
      id: yarn_cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn_cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('apps/mobile/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        cd apps/mobile
        yarn install

  build-ios:
    needs: setup
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: apps/mobile

    - name: Install react-native-cli
      run: |
        cd apps/mobile
        yarn global add react-native-cli

    - name: Build React Native iOS app
      run: |
        cd apps/mobile
        react-native run-ios --no-packager

  build-android:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: apps/mobile

    - name: Install react-native-cli
      run: |
        cd apps/mobile
        yarn global add react-native-cli

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Build React Native Android app
      run: |
        cd apps/mobile
        react-native run-android --no-packager
